server:
  port: 8083
spring:
#Asyc communication between services when using rabbitmq and cloud stream
  rabbitmq:
    #host: 192.168.99.100
    host: localhost
    port: 5672
#Asyc communication between services when using cloud stream and rabbit mq
  cloud:
    stream:
      bindings:
        login-out:
          destination: login
          group: login
    config:
      uri: ${config.uri:http://localhost:8888}
      
      prefix: /          
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true     
#custom property - to be put under config server
jwt:
 secret: javainuse
 transaction-secret: tranSecret
 

   
 